/** Declaration file generated by dts-gen */
declare module 'diffParser' {
export = diffparser;
}
declare function diffparser(input: any, ...args: any[]): any;

declare namespace diffparser {
    const prototype: {
    };

}

declare interface Chunk {
    readonly changes: LineInfo[];
}


declare interface LineInfo {
    readonly type: string;
    readonly content: string;
    readonly oldLine: number;
    readonly newLine: number;
    readonly position: number;
    readonly add: boolean;
    readonly del: boolean;
}
