/** Declaration file generated by dts-gen */
declare module 'easy-spawn' {
    
    export = Spawn;
}

declare class Spawn {
    constructor(options: any);

    cmd(cmd: any, callback: (error: string|null, data: string|null)=>(void) ): any;

    endSession(): any;

    getOption(key: any, defaultValue: any, ...args: any[]): any;

    option(...args: any[]): any;

    session(...args: any[]): any;

    static joinParams(addParams: string[], params : string[]): string[];

}

declare interface DefaultOptions {
    readonly program?: string;
    readonly cwd?: string;
    readonly silent?: boolean;
}